/* Generated by Together */

package net.grinder.statistics;

import java.util.List;
public class StatisticsView {
    public void add(ExpressionView statistic) {
    }

    /**
     *@link aggregation
     *      @associates <{net.grinder.statistics.ExpressionView}>
     * @supplierCardinality 0..*
     */
    private List m_columns;
}
